require("dotenv").config();
const {
  PORT,
  MONGO_URL,
  BOT_TOKEN,
  CLIENT_ID,
  API_KEY,
  CONTRACT_ADDRESS_ECO,
  CONTRACT_ADDRESS_ECOX,
  CONTRACT_DIGIT,
  EXPLORER_URL,
  SERVER_ID,
  ADMIN_ID,
  TICKET_VALUE,
  CURRENCY_NAME_ECO,
  TOTAL_SUPPLY_ECO,
  CONTRACT_FEE_ECO,
  CURRENCY_NAME_ECOX,
  TOTAL_SUPPLY_ECOX,
  CONTRACT_FEE_ECOX,
  TX_CHANNEL_ID,
} = process.env;

// System config Data
const config = {
  PORT,
  MONGO_URL,
  BOT_TOKEN,
  CLIENT_ID,
  API_KEY,
  CONTRACT_ADDRESS_ECO,
  CONTRACT_ADDRESS_ECOX,
  CONTRACT_DIGIT,
  EXPLORER_URL,
  SERVER_ID,
  ADMIN_ID,
  TICKET_VALUE: TICKET_VALUE || 100,
  CURRENCY: {
    ECO: {
      NAME: process.env.CURRENCY_NAME_ECO || "ECO",
      TOKEN_ADDRESS: process.env.CONTRACT_ADDRESS_ECO || "",
      TOTAL_SUPPLY: process.env.TOTAL_SUPPLY_ECO,
      FEE: CONTRACT_FEE_ECO,
    },
    ECOX: {
      NAME: process.env.CURRENCY_NAME_ECOX || "ECOX_TEST",
      TOKEN_ADDRESS: process.env.CONTRACT_ADDRESS_ECOX || "",
      TOTAL_SUPPLY: process.env.TOTAL_SUPPLY_ECOX,
      FEE: CONTRACT_FEE_ECOX,
    },
  },
  TX_CHANNEL_ID: TX_CHANNEL_ID || "1091888045034319912",
};
module.exports = config;
